[tools]
ruby = "4.0.2"
communique = "0.1.9"

[env]
_.file = ".env"

[tasks.test]
run = "bundle exec rake test"

[tasks.lint]
run = "bundle exec standardrb"

[tasks.release-test]
run = "exe/puma-release --release-repo nateberkopec/puma --repo-dir ../../upstream/puma"

[tasks.release-live]
run = "exe/puma-release --live --repo-dir ../../upstream/puma"
